### ISSUE TITLE
Request to Update multichannel-widget for Compatibility with Jetifier Disabled

### ISSUE THREAD

**Issue by zuhriyansauqi** [qiscus/qiscus-multichannel-widget-android#11]
Dear Qiscus Development Team,

I am currently using the `multichannel-widget` version `2.2.1` in my Android project. I noticed that this library requires legacy support libraries, as indicated by the need for Jetifier to be enabled. This requirement increases our project's build time significantly.

In line with modern Android development practices and to enhance build performance, I kindly request that the `multichannel-widget` library be updated to be compatible with AndroidX without the need for Jetifier. 

This change would be greatly appreciated by many developers who strive for more efficient build times and modern library practices. Attached is a screenshot from my build's analysis that indicates the dependency on legacy support libraries.

<img width="894" alt="image" src="https://github.com/qiscus/qiscus-multichannel-widget-android/assets/4607523/c9555e82-2b46-4cd5-8265-3ca40d912f8b">

Thank you for considering this request. I am looking forward to the improved version of the `multichannel-widget`.

Best regards,
Ryan

**Comment by ariefnurputranto** [comment]
hi @zuhriyansauqi , Thank you for your feedback. 

we will update in the next release

Best regards,
Arief

**Comment by zuhriyansauqi** [comment]
Hi @ariefnurputranto, thanks for the update. I have a question, though: What is the function of SCHEDULE_EXACT_ALARM? It seems that the chat feature now requires this permission to function.
