### ISSUE TITLE
Jcenter Issue

### ISSUE THREAD

**Issue by hafiznaufalr** [qiscus/qiscus-multichannel-widget-android#6]
Hello guys, I have an issue when integrating qiscus widget, I think the problem is the dependency library to Jcenter, there is an error from some libraries that I think still get from Jcenter, because when I see the step to integrate is need Jcenter in build.gradle, but my project is not using Jcenter anymore because it's already shutting down the service.

and this is what happens when I run the project:
![image](https://user-images.githubusercontent.com/35401886/143986117-bcf13458-1c2e-4b9f-a7cf-006f4aa47e75.png)

**Comment by ariefnurputranto** [comment]
Hi @hafiznaufalr, 
you can run the project by adding the code
```
Jcenter()
```
like the code in the example

Thanks
