### ISSUE TITLE
Custom static title

### ISSUE THREAD

**Issue by hafiznaufalr** [qiscus/qiscus-multichannel-widget-android#7]
I have an Issue in version 2.0.1, I already set the custom title:
.setRoomTitle("Custom Title")

but the title is still get from name in setUser function.

**Comment by ariefnurputranto** [comment]
hi @hafiznaufalr , 

Thanks for your report,

We have released in this version 
```https://github.com/qiscus/qiscus-multichannel-widget-android/releases/tag/2.0.2```

**Comment by hafiznaufalr** [comment]
Thank You for the new release, it works now! @ariefnurputranto
